### ISSUE TITLE
datetime field not functioning

### ISSUE THREAD

**Issue by ckadams** [WedgeSama/array-field-type-extension#5]
When the type is datetime, the field appears, but the datepicker does not function.  Does anyone have any ideas on how to get this to function?

**Comment by mrmnml** [comment]
I noticed the same issue. If i find a work around I'll let you know

**Comment by mrmnml** [comment]
edit: Ok, I think this is the part that made it work, disregard the rest:
1. on the page where you edit your content, add a few items to the date time array
2. without editing them, save the entry
3. reload the page
4. datepicker works now

repeat if you want to add new items

---

Strange, it's working now. Don't know if you can reproduce this, but I 
1. added another regular datetime field to the content type
2. reloaded the page
3. opened the datepicker for the new field
4. added & opened the datepicker for an array field type item
5. saved (& ignored the error message because I didn't update my db)
6. removed the new datetime field
7. ???
8. profit

Now it works for me.

**Comment by ckadams** [comment]
Yes, If there is data, then reloading the page will allow the datepicker to load properly.  However, the next field will fail again until you manually add data, save and reload.  That is not an option, as it is not very usable.

An option is to include a random ID in <input> and call the datepicker again (passing the new id)  in javascript after the <input> is visible in the DOM.  I just haven't walked through the code to find out where the best place to set the ID might be.  Might work, might not.  I'm certain there's a simpler solution.

Thanks for your input!

**Comment by WedgeSama** [comment]
I reproduice the problem too and found were it is.

When I dev the extension, it was only to be use with "simple" type (no javascript call) and with others field type extentions where javascript code is write in template (so it is call directly when click the Add button). This is why I did not noticed it.

For base types with use of javascript, the code is located in the `bolt.min.js` and run only once: at page loading. So this is why it not works as expected.

I will take a closer look to find a way to make it works correctly.

**Comment by WedgeSama** [comment]
I made some fix about this issue. You can see on the `README` which base field types work or not. For date and datetime, it is now OK.

Can you test with the `dev-master`? I will create a new tag after your feedback.

**Comment by ckadams** [comment]
Excellent work!  I tested add, delete, update with numerous datetime fields and they appear to be functioning. Thank you very much!

**Comment by WedgeSama** [comment]
Now 1.0.3 released and solve the original problem.
